name: Build APK

on: [push, workflow_dispatch]

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            zip \
            unzip \
            openjdk-11-jdk \
            git \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            cmake
        pip install buildozer cython==0.29.19
    
    - name: Initialize Buildozer
      run: |
        buildozer init
        # Update buildozer.spec with your configuration
        echo "[app]
title = MyApp
package.name = myapp
package.domain = org.mydomain
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy==2.0.0,kivymd
orientation = portrait
android.api = 30
android.minapi = 21
android.ndk = 19b
android.sdk = 26
android.arch = armeabi-v7a" > buildozer.spec
    
    - name: Build APK
      run: |
        buildozer -v android debug
        mkdir dist
        cp bin/*.apk dist/
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: dist/*.apk
