name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=DATE::$(date +'%Y%m%d')"
        shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            python -m pip install -r requirements.txt;
          fi
          python -m pip install "kivy[full]"
          python -m pip install cython==0.29.36
          python -m pip install -U setuptools wheel
          python -m pip install buildozer
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: "latest"
          accept-android-sdk-licenses: true
          platform-tools: true
          build-tools: "33.0.2"
          platforms: "android-33"
      - name: Add Android SDK to PATH
        run: |
          echo "Adding $ANDROID_HOME/platform-tools and $ANDROID_HOME/build-tools/33.0.2 to PATH"
          export PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH"
          echo "Updated PATH: $PATH"
          command -v aidl
      - name: Verify aidl
        env:
          PATH: "$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH"
        run: |
          echo "Verifying aidl installation"
          if command -v aidl; then
            echo "aidl found in PATH: $(command -v aidl)"
            aidl
          else
            echo "aidl not found in PATH"
            exit 1
          fi
      - name: Initialize Buildozer
        run: |
          if [ ! -f "buildozer.spec" ]; then
            buildozer init;
          fi
      - name: Build APK
        run: |
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get-date.outputs.DATE }}-android-apk
          path: bin/*.apk
      - name: Show Buildozer Output
        if: failure()
        run: |
          echo "Buildozer Output:"
          cat .buildozer/app.log
