name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "kivy[full]"
          python -m pip install cython==0.29.36
          python -m pip install -U setuptools wheel
          python -m pip install buildozer
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools: "latest"
          accept-android-sdk-licenses: true
          components: build-tools;33.0.2,platform-tools,platforms;android-33

      - name: Debug PATH
        run: echo "$PATH"

      - name: Debug ANDROID_HOME
        run: echo "$ANDROID_HOME"

      - name: List Build Tools
        run: ls $ANDROID_HOME/build-tools/33.0.2

      - name: Verify AIDL installation
        run: |
          echo "Verifying aidl installation"
          if command -v aidl; then
            echo "aidl found in PATH: $(command -v aidl)"
            aidl --version
          else
            echo "aidl not found in PATH"
            exit 1
          fi
      - name: Build APK
        run: |
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
      - name: Show Buildozer Output
        if: failure()
        run: |
          echo "Buildozer Output:"
          cat .buildozer/app.log
